"""Конфигурация приложения"""
from .config import (
    GIGACHAT_API_KEY,
    ROCKETCHAT_API_KEY,
    ROCKETCHAT_URL,
    LLM_MODEL,
    LLM_TEMPERATURE,
    LLM_MAX_TOKENS,
    MAX_PROJECT_SUGGESTIONS,
    PROJECT_CONFIRMATION_REQUIRED,
    PROMPTS_DIR,
    CONTENT_DIR,
    PROJECT_ROOT,
)

__all__ = [
    "GIGACHAT_API_KEY",
    "ROCKETCHAT_API_KEY",
    "ROCKETCHAT_URL",
    "LLM_MODEL",
    "LLM_TEMPERATURE",
    "LLM_MAX_TOKENS",
    "MAX_PROJECT_SUGGESTIONS",
    "PROJECT_CONFIRMATION_REQUIRED",
    "PROMPTS_DIR",
    "CONTENT_DIR",
    "PROJECT_ROOT",
]
